name: Boilerplate Upgrade Automation
on:
  workflow_dispatch:

jobs:
  trigger-upgrade:
    name: Boilerplate Upgrade Automation
    uses: ./.github/workflows/nebula_automation.yml

    with:
      component: boilerplate
    secrets:
      NEBULA_BOT_PAT: ${{ secrets.NEBULA_BOT_PAT }}